import type { ImageMetadata } from "@tamil-ulagam/shared";

export const images = {
  homeHero: {
    path: "/images/tamil-ulagam/home/home-hero-desktop.png",
    mobilePath: "/images/tamil-ulagam/home/home-hero-mobile.png",
    alt: "People across generations representing Tamil communities connected around the world",
    width: 1672,
    height: 941,
    aspectRatio: "16/9",
    mobileWidth: 941,
    mobileHeight: 1672,
    mobileAspectRatio: "9/16",
    objectPosition: "70% 50%",
    mobileObjectPosition: "60% 70%",
    aboveFold: true,
    mobileAlternative: true,
    available: true,
  },
  whyTamilUlagam: {
    path: "/images/tamil-ulagam/home/why-tamil-ulagam.png",
    alt: "Montage of people learning, working, creating, and gathering across global cities",
    width: 1448,
    height: 1086,
    aspectRatio: "4/3",
    objectPosition: "center",
    aboveFold: false,
    mobileAlternative: false,
    available: true,
  },
  finalCallToAction: {
    path: "/images/tamil-ulagam/home/final-cta.png",
    alt: "Multi-generational group gathered beside a world map at sunset",
    width: 1672,
    height: 941,
    aspectRatio: "16/9",
    objectPosition: "65% 50%",
    aboveFold: false,
    mobileAlternative: false,
    available: true,
  },
  pillarConnect: {
    path: "/images/tamil-ulagam/pillars/pillar-connect.png",
    alt: "People of different generations in conversation around a table",
    width: 1086,
    height: 1448,
    aspectRatio: "3/4",
    objectPosition: "center",
    aboveFold: false,
    mobileAlternative: false,
    available: true,
  },
  pillarEmpower: {
    path: "/images/tamil-ulagam/pillars/pillar-empower.png",
    alt: "Professional team collaborating around a laptop and planning board",
    width: 1086,
    height: 1448,
    aspectRatio: "3/4",
    objectPosition: "center",
    aboveFold: false,
    mobileAlternative: false,
    available: true,
  },
  pillarPreserve: {
    path: "/images/tamil-ulagam/pillars/pillar-preserve.png",
    alt: "An elder sharing a manuscript with younger listeners in a library",
    width: 1086,
    height: 1448,
    aspectRatio: "3/4",
    objectPosition: "center",
    aboveFold: false,
    mobileAlternative: false,
    available: true,
  },
  initiativeHealthcare: {
    path: "/images/tamil-ulagam/initiatives/initiative-healthcare.png",
    alt: "A clinician listening to a patient during a consultation",
    width: 1448,
    height: 1086,
    aspectRatio: "4/3",
    objectPosition: "center",
    aboveFold: false,
    mobileAlternative: false,
    available: true,
  },
  initiativeEducation: {
    path: "/images/tamil-ulagam/initiatives/initiative-education.png",
    alt: "An educator guiding students using books, a laptop, and a tablet",
    width: 1448,
    height: 1086,
    aspectRatio: "4/3",
    objectPosition: "center",
    aboveFold: false,
    mobileAlternative: false,
    available: true,
  },
  initiativeBusiness: {
    path: "/images/tamil-ulagam/initiatives/initiative-business.png",
    alt: "Professionals in discussion in a modern meeting space",
    width: 1448,
    height: 1086,
    aspectRatio: "4/3",
    objectPosition: "60% 50%",
    aboveFold: false,
    mobileAlternative: false,
    available: true,
  },
  initiativeJobs: {
    path: "/images/tamil-ulagam/initiatives/initiative-jobs.png",
    alt: "Two professionals having a career conversation in a bright office",
    width: 1448,
    height: 1086,
    aspectRatio: "4/3",
    objectPosition: "65% 50%",
    aboveFold: false,
    mobileAlternative: false,
    available: true,
  },
  initiativeResearch: {
    path: "/images/tamil-ulagam/initiatives/initiative-research.png",
    alt: "A research team examining archival materials and equipment",
    width: 1448,
    height: 1086,
    aspectRatio: "4/3",
    objectPosition: "center",
    aboveFold: false,
    mobileAlternative: false,
    available: true,
  },
  initiativeTourism: {
    path: "/images/tamil-ulagam/initiatives/initiative-tourism.png",
    alt: "Visitors being welcomed in a heritage-style courtyard",
    width: 1448,
    height: 1086,
    aspectRatio: "4/3",
    objectPosition: "center",
    aboveFold: false,
    mobileAlternative: false,
    available: true,
  },
  initiativeArtsCulture: {
    path: "/images/tamil-ulagam/initiatives/initiative-arts-culture.png",
    alt: "A dancer, musician, sculptor, and painter practising Tamil art forms",
    width: 1448,
    height: 1086,
    aspectRatio: "4/3",
    objectPosition: "center",
    aboveFold: false,
    mobileAlternative: false,
    available: true,
  },
  initiativeGlobalEvents: {
    path: "/images/tamil-ulagam/initiatives/initiative-global-events.png",
    alt: "Attendees in conversation at an international conference",
    width: 1448,
    height: 1086,
    aspectRatio: "4/3",
    objectPosition: "center",
    aboveFold: false,
    mobileAlternative: false,
    available: true,
  },
  tamilIdShowcase: {
    path: "/images/tamil-ulagam/membership/tamil-id-showcase.png",
    alt: "Concept design of a Tamil ID card held against a navy background",
    width: 1086,
    height: 1448,
    aspectRatio: "3/4",
    objectPosition: "center",
    aboveFold: false,
    mobileAlternative: false,
    available: true,
  },
  globalChapters: {
    path: "/images/tamil-ulagam/chapters/global-chapters.png",
    alt: "Illuminated globe with connection lines across regions",
    width: 1672,
    height: 941,
    aspectRatio: "16/9",
    objectPosition: "70% 50%",
    aboveFold: false,
    mobileAlternative: false,
    available: true,
  },
  partnerships: {
    path: "/images/tamil-ulagam/pages/partnerships.png",
    alt: "Professionals discussing collaboration around a conference table",
    width: 1448,
    height: 1086,
    aspectRatio: "4/3",
    objectPosition: "center",
    aboveFold: false,
    mobileAlternative: false,
    available: true,
  },
  communityStories: {
    path: "/images/tamil-ulagam/pages/community-stories.png",
    alt: "An older speaker sharing knowledge with a multi-generational group",
    width: 1448,
    height: 1086,
    aspectRatio: "4/3",
    objectPosition: "center",
    aboveFold: false,
    mobileAlternative: false,
    available: true,
  },
  aboutHero: {
    path: "/images/tamil-ulagam/pages/about-hero.png",
    alt: "People across generations looking ahead beside global and Tamil cultural imagery",
    width: 1672,
    height: 941,
    aspectRatio: "16/9",
    objectPosition: "70% 50%",
    aboveFold: true,
    mobileAlternative: false,
    available: true,
  },
  roadmapFuture: {
    path: "/images/tamil-ulagam/pages/roadmap-future.png",
    alt: "People gathered around an elder with global imagery and open space for future direction",
    width: 1672,
    height: 941,
    aspectRatio: "16/9",
    objectPosition: "70% 50%",
    aboveFold: false,
    mobileAlternative: false,
    available: true,
  },
  mobileAppPreview: {
    path: "/images/tamil-ulagam/pages/mobile-app-preview.png",
    alt: "Concept mobile app interface presented in a community setting",
    width: 1086,
    height: 1448,
    aspectRatio: "3/4",
    objectPosition: "65% 50%",
    aboveFold: false,
    mobileAlternative: false,
    available: true,
  },
} as const satisfies Record<string, ImageMetadata>;

export type ImageKey = keyof typeof images;

/**
 * Editorial media that must remain visible and decoded after a complete
 * homepage scroll. This keeps browser verification aligned with the registry.
 */
export const homepageEditorialImageKeys = [
  "whyTamilUlagam",
  "tamilIdShowcase",
  "globalChapters",
  "roadmapFuture",
  "mobileAppPreview",
  "partnerships",
  "communityStories",
  "finalCallToAction",
] as const satisfies readonly ImageKey[];

export const aboutEditorialImageKeys = [
  "aboutHero",
  "partnerships",
  "roadmapFuture",
] as const satisfies readonly ImageKey[];

export const tamilIdEditorialImageKeys = [
  "tamilIdShowcase",
] as const satisfies readonly ImageKey[];

export const chaptersEditorialImageKeys = [
  "globalChapters",
  "partnerships",
] as const satisfies readonly ImageKey[];

export const roadmapEditorialImageKeys = [
  "roadmapFuture",
] as const satisfies readonly ImageKey[];

export const partnersEditorialImageKeys = [
  "partnerships",
] as const satisfies readonly ImageKey[];

export const initiativesEditorialImageKeys = [
  "initiativeHealthcare",
  "initiativeEducation",
  "initiativeBusiness",
  "initiativeJobs",
  "initiativeResearch",
  "initiativeTourism",
  "initiativeArtsCulture",
  "initiativeGlobalEvents",
] as const satisfies readonly ImageKey[];

export function getImage(key: ImageKey): ImageMetadata {
  return images[key];
}
