import type { ImageMetadata } from "@tamil-ulagam/shared";

export const images = {
  homeHero: {
    path: "/images/tamil-ulagam/home/home-hero-desktop.png",
    mobilePath: "/images/tamil-ulagam/home/home-hero-mobile.png",
    alt: "People across generations representing Tamil communities connected around the world",
    width: 1672,
    height: 941,
    aspectRatio: "16/9",
    mobileWidth: 941,
    mobileHeight: 1672,
    mobileAspectRatio: "9/16",
    objectPosition: "70% 50%",
    mobileObjectPosition: "60% 70%",
    aboveFold: true,
    mobileAlternative: true,
    available: true,
  },
  whyTamilUlagam: {
    path: "/images/tamil-ulagam/home/why-tamil-ulagam.png",
    alt: "Montage of people learning, working, creating, and gathering across global cities",
    width: 1448,
    height: 1086,
    aspectRatio: "4/3",
    objectPosition: "center",
    aboveFold: false,
    mobileAlternative: false,
    available: true,
  },
  finalCallToAction: {
    path: "/images/tamil-ulagam/home/final-cta.png",
    alt: "Multi-generational group gathered beside a world map at sunset",
    width: 1672,
    height: 941,
    aspectRatio: "16/9",
    objectPosition: "65% 50%",
    aboveFold: false,
    mobileAlternative: false,
    available: true,
  },
  pillarConnect: {
    path: "/images/tamil-ulagam/pillars/pillar-connect.png",
    alt: "People of different generations in conversation around a table",
    width: 1086,
    height: 1448,
    aspectRatio: "3/4",
    objectPosition: "center",
    aboveFold: false,
    mobileAlternative: false,
    available: true,
  },
  pillarEmpower: {
    path: "/images/tamil-ulagam/pillars/pillar-empower.png",
    alt: "Professional team collaborating around a laptop and planning board",
    width: 1086,
    height: 1448,
    aspectRatio: "3/4",
    objectPosition: "center",
    aboveFold: false,
    mobileAlternative: false,
    available: true,
  },
  pillarPreserve: {
    path: "/images/tamil-ulagam/pillars/pillar-preserve.png",
    alt: "An elder sharing a manuscript with younger listeners in a library",
    width: 1086,
    height: 1448,
    aspectRatio: "3/4",
    objectPosition: "center",
    aboveFold: false,
    mobileAlternative: false,
    available: true,
  },
  initiativeHealthcare: {
    path: "/images/tamil-ulagam/initiatives/initiative-healthcare.jpg",
    alt: "Doctor examines child's chest with stethoscope",
    width: 1600,
    height: 900,
    aspectRatio: "16/9",
    objectPosition: "center",
    aboveFold: false,
    mobileAlternative: false,
    available: true,
  },
  initiativeEducation: {
    path: "/images/tamil-ulagam/initiatives/initiative-education.jpg",
    alt: "A group of children sitting at desks in a classroom",
    width: 1600,
    height: 1067,
    aspectRatio: "1600/1067",
    objectPosition: "center",
    aboveFold: false,
    mobileAlternative: false,
    available: true,
  },
  initiativeBusiness: {
    path: "/images/tamil-ulagam/initiatives/initiative-business.jpg",
    alt: "Street vendor selling colorful goods to customers",
    width: 1600,
    height: 900,
    aspectRatio: "16/9",
    objectPosition: "center",
    aboveFold: false,
    mobileAlternative: false,
    available: true,
  },
  initiativeJobs: {
    path: "/images/tamil-ulagam/initiatives/initiative-jobs.jpg",
    alt: "four coworkers smiling around laptop at table",
    width: 1600,
    height: 1067,
    aspectRatio: "1600/1067",
    objectPosition: "center",
    aboveFold: false,
    mobileAlternative: false,
    available: true,
  },
  initiativeResearch: {
    path: "/images/tamil-ulagam/initiatives/initiative-research.jpg",
    alt: "A person in a white lab coat looking through a microscope in a laboratory",
    width: 1600,
    height: 1040,
    aspectRatio: "20/13",
    objectPosition: "center",
    aboveFold: false,
    mobileAlternative: false,
    available: true,
  },
  initiativeTourism: {
    path: "/images/tamil-ulagam/initiatives/initiative-tourism.jpg",
    alt: "An ornate ancient indian temple gopuram at sunset",
    width: 1600,
    height: 1101,
    aspectRatio: "1600/1101",
    objectPosition: "center",
    aboveFold: false,
    mobileAlternative: false,
    available: true,
  },
  initiativeArtsCulture: {
    path: "/images/tamil-ulagam/initiatives/initiative-arts-culture.jpg",
    alt: "Young dancer in traditional indian costume performs gracefully",
    width: 1600,
    height: 1067,
    aspectRatio: "1600/1067",
    objectPosition: "center",
    aboveFold: false,
    mobileAlternative: false,
    available: true,
  },
  initiativeGlobalEvents: {
    path: "/images/tamil-ulagam/initiatives/initiative-global-events.jpg",
    alt: "group of people in front of stage",
    width: 1600,
    height: 1200,
    aspectRatio: "4/3",
    objectPosition: "center",
    aboveFold: false,
    mobileAlternative: false,
    available: true,
  },
  tamilIdShowcase: {
    path: "/images/tamil-ulagam/membership/tamil-id-showcase.png",
    alt: "Digital Tamil ID membership card held against a navy background",
    width: 1086,
    height: 1448,
    aspectRatio: "3/4",
    objectPosition: "center",
    aboveFold: false,
    mobileAlternative: false,
    available: true,
  },
  globalChapters: {
    path: "/images/tamil-ulagam/chapters/global-chapters.png",
    alt: "Illuminated globe with connection lines across regions",
    width: 1672,
    height: 941,
    aspectRatio: "16/9",
    objectPosition: "70% 50%",
    aboveFold: false,
    mobileAlternative: false,
    available: true,
  },
  partnerships: {
    path: "/images/tamil-ulagam/pages/partnerships.png",
    alt: "Professionals discussing collaboration around a conference table",
    width: 1448,
    height: 1086,
    aspectRatio: "4/3",
    objectPosition: "center",
    aboveFold: false,
    mobileAlternative: false,
    available: true,
  },
  communityStories: {
    path: "/images/tamil-ulagam/pages/community-stories.png",
    alt: "An older speaker sharing knowledge with a multi-generational group",
    width: 1448,
    height: 1086,
    aspectRatio: "4/3",
    objectPosition: "center",
    aboveFold: false,
    mobileAlternative: false,
    available: true,
  },
  aboutHero: {
    path: "/images/tamil-ulagam/pages/about-hero.png",
    alt: "People across generations looking ahead beside global and Tamil cultural imagery",
    width: 1672,
    height: 941,
    aspectRatio: "16/9",
    objectPosition: "70% 50%",
    aboveFold: true,
    mobileAlternative: false,
    available: true,
  },
  roadmapFuture: {
    path: "/images/tamil-ulagam/pages/roadmap-future.png",
    alt: "People gathered around an elder with global imagery and open space for future direction",
    width: 1672,
    height: 941,
    aspectRatio: "16/9",
    objectPosition: "70% 50%",
    aboveFold: false,
    mobileAlternative: false,
    available: true,
  },
  mobileAppPreview: {
    path: "/images/tamil-ulagam/pages/mobile-app-preview.png",
    alt: "Tamil Ulagam mobile app interface visual presented in a community setting",
    width: 1086,
    height: 1448,
    aspectRatio: "3/4",
    objectPosition: "65% 50%",
    aboveFold: false,
    mobileAlternative: false,
    available: true,
  },
  portalAuthHero: {
    path: "/images/tamil-ulagam/portal/portal-auth-hero-tamil.png",
    alt: "Tamil people across generations gathered in conversation in a contemporary home",
    width: 1122,
    height: 1402,
    aspectRatio: "1122/1402",
    objectPosition: "50% 50%",
    aboveFold: false,
    mobileAlternative: false,
    available: true,
  },
  portalDashboardVisual: {
    path: "/images/tamil-ulagam/portal/portal-dashboard-visual.png",
    alt: "Community representatives gathered in discussion beside a world map",
    width: 1448,
    height: 1086,
    aspectRatio: "4/3",
    objectPosition: "72% 50%",
    aboveFold: false,
    mobileAlternative: false,
    available: true,
  },
  portalRegistrationIntro: {
    path: "/images/tamil-ulagam/portal/portal-registration-intro.png",
    alt: "A multi-generational group collaborating in a professional community setting",
    width: 1672,
    height: 941,
    aspectRatio: "16/9",
    objectPosition: "72% 50%",
    aboveFold: false,
    mobileAlternative: false,
    available: true,
  },
  portalBackgroundMotif: {
    path: "/images/tamil-ulagam/portal/portal-background-motif.png",
    alt: "Tamil Ulagam geometric portal motif",
    width: 1672,
    height: 941,
    aspectRatio: "16/9",
    objectPosition: "center",
    aboveFold: false,
    mobileAlternative: false,
    available: true,
  },
  eventTamilUlagamDay: {
    path: "/images/tamil-ulagam/events/tamil-ulagam-day.jpg",
    alt: "Tamil communities gathered in traditional dress at a festival procession",
    width: 1800,
    height: 1199,
    aspectRatio: "1800/1199",
    objectPosition: "center",
    aboveFold: false,
    mobileAlternative: false,
    available: true,
  },
  eventPongal: {
    path: "/images/tamil-ulagam/events/pongal.jpg",
    alt: "A large coloured kolam drawn on the ground for the harvest festival",
    width: 1800,
    height: 1197,
    aspectRatio: "200/133",
    objectPosition: "center",
    aboveFold: false,
    mobileAlternative: false,
    available: true,
  },
  eventTamilNewYear: {
    path: "/images/tamil-ulagam/events/tamil-new-year.jpg",
    alt: "Lit clay oil lamps arranged on a tray with scattered flower petals",
    width: 1800,
    height: 1200,
    aspectRatio: "3/2",
    objectPosition: "center",
    aboveFold: false,
    mobileAlternative: false,
    available: true,
  },
  eventGlobalSummit: {
    path: "/images/tamil-ulagam/events/global-summit.jpg",
    alt: "A speaker addressing a full auditorium at a community summit",
    width: 1800,
    height: 1013,
    aspectRatio: "1800/1013",
    objectPosition: "center",
    aboveFold: false,
    mobileAlternative: false,
    available: true,
  },
  eventHeritageMonth: {
    path: "/images/tamil-ulagam/events/heritage-month.jpg",
    alt: "A carved Tamil temple gopuram rising against a night sky full of stars",
    width: 1800,
    height: 1200,
    aspectRatio: "3/2",
    objectPosition: "center",
    aboveFold: false,
    mobileAlternative: false,
    available: true,
  },
  eventAwardsNight: {
    path: "/images/tamil-ulagam/events/awards-night.jpg",
    alt: "Gold and maroon trophies set out before an awards ceremony",
    width: 1800,
    height: 1200,
    aspectRatio: "3/2",
    objectPosition: "center",
    aboveFold: false,
    mobileAlternative: false,
    available: true,
  },
  newsroom: {
    path: "/images/tamil-ulagam/news/newsroom.jpg",
    alt: "An open handwritten ledger, close up",
    width: 1800,
    height: 1352,
    aspectRatio: "225/169",
    objectPosition: "center",
    aboveFold: false,
    mobileAlternative: false,
    available: true,
  },
  newsCommunityStory: {
    path: "/images/tamil-ulagam/news/community-story.jpg",
    alt: "A performer in traditional Tamil costume and makeup at a festival",
    width: 1800,
    height: 1200,
    aspectRatio: "3/2",
    objectPosition: "center",
    aboveFold: false,
    mobileAlternative: false,
    available: true,
  },
  newsGlobalNetwork: {
    path: "/images/tamil-ulagam/news/global-network.jpg",
    alt: "The earth seen from space at night, city lights marking the continents",
    width: 1800,
    height: 1013,
    aspectRatio: "1800/1013",
    objectPosition: "center",
    aboveFold: false,
    mobileAlternative: false,
    available: true,
  },
} as const satisfies Record<string, ImageMetadata>;

export type ImageKey = keyof typeof images;

export const homepageEditorialImageKeys = [
  "finalCallToAction",
  "pillarConnect",
  "pillarEmpower",
  "pillarPreserve",
  "initiativeHealthcare",
  "initiativeEducation",
  "initiativeBusiness",
  "initiativeJobs",
  "globalChapters",
] as const satisfies readonly ImageKey[];

export const aboutEditorialImageKeys: readonly ImageKey[] = [];

export const tamilIdEditorialImageKeys: readonly ImageKey[] = [];

export const chaptersEditorialImageKeys: readonly ImageKey[] = [];

export const partnersEditorialImageKeys: readonly ImageKey[] = [];

export const eventsEditorialImageKeys = [
  "eventTamilUlagamDay",
  "eventPongal",
  "eventTamilNewYear",
  "eventGlobalSummit",
  "eventHeritageMonth",
  "eventAwardsNight",
] as const satisfies readonly ImageKey[];

export const newsEditorialImageKeys = [
  "newsroom",
  "newsCommunityStory",
  "newsGlobalNetwork",
] as const satisfies readonly ImageKey[];

export const initiativesEditorialImageKeys = [
  "initiativeHealthcare",
  "initiativeEducation",
  "initiativeBusiness",
  "initiativeJobs",
  "initiativeResearch",
  "initiativeTourism",
  "initiativeArtsCulture",
  "initiativeGlobalEvents",
] as const satisfies readonly ImageKey[];
