import type { ImageMetadata } from "@tamil-ulagam/shared";

export const joinImages = {
  joinHubHero: {
    path: "/images/tamil-ulagam/join/join-hub-hero.webp",
    mobilePath: "/images/tamil-ulagam/join/join-hub-hero-mobile.webp",
    alt: "Abstract Federation Night gradient composition — deep navy blending into a restrained maroon glow, with fine kolam-derived gold linework",
    width: 1916,
    height: 821,
    aspectRatio: "1916/821",
    mobileWidth: 657,
    mobileHeight: 821,
    mobileAspectRatio: "657/821",
    objectPosition: "70% 50%",
    mobileObjectPosition: "center",
    aboveFold: true,
    mobileAlternative: true,
    available: true,
  },
  organisationJourneyHero: {
    path: "/images/tamil-ulagam/join/organisation-journey-hero.webp",
    alt: "Elegant carved stone architectural detail in warm late-afternoon light, evoking institutional permanence and craftsmanship",
    width: 1448,
    height: 1086,
    aspectRatio: "4/3",
    objectPosition: "center",
    aboveFold: true,
    mobileAlternative: false,
    available: true,
  },
  sangamJourneyHero: {
    path: "/images/tamil-ulagam/join/sangam-journey-hero.webp",
    alt: "A traditional brass oil lamp and kolam-patterned inlaid table in a contemporary home, with a global city skyline visible through the window at dusk",
    width: 1448,
    height: 1086,
    aspectRatio: "4/3",
    objectPosition: "center",
    aboveFold: true,
    mobileAlternative: false,
    available: true,
  },
} as const satisfies Record<string, ImageMetadata>;
