-- Lean V2 registration: additive, backward-compatible changes only.
-- Adds organisation-email verification, platform terms consent, and
-- lightweight duplicate-organisation signals. Does not remove or narrow
-- any existing column, table, policy, or grant.

-- ---------------------------------------------------------------------
-- 1. New columns (all nullable; existing rows receive NULL naturally)
-- ---------------------------------------------------------------------

alter table public.profiles
  add column if not exists terms_accepted_at timestamptz;

alter table public.organizations
  add column if not exists official_email_verified_at timestamptz,
  add column if not exists official_email_verification_sent_at timestamptz;

-- ---------------------------------------------------------------------
-- 2. Platform terms consent at signup.
--
-- The client passes a "terms_accepted" flag through auth signUp()
-- user_metadata (never a client-supplied timestamp — the server clock
-- is authoritative). The trigger is replaced additively; its insert
-- behaviour for existing columns is unchanged.
-- ---------------------------------------------------------------------

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, full_name, phone, terms_accepted_at)
  values (
    new.id,
    coalesce(left(nullif(btrim(new.raw_user_meta_data ->> 'full_name'), ''), 160), ''),
    coalesce(left(new.phone, 50), ''),
    case
      when new.raw_user_meta_data ->> 'terms_accepted' = 'true' then now()
      else null
    end
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

-- ---------------------------------------------------------------------
-- 3. Organisation-email verification.
--
-- Proves control of the organisation's declared official contact inbox,
-- distinct from Supabase account-email confirmation. The raw token is
-- never returned to a browser-callable function: it is only ever
-- generated by a service-role-only function (called from the Edge
-- Function that emails it), and only ever consumed by presenting that
-- same token back through a narrow, rate-limited-by-expiry function.
-- ---------------------------------------------------------------------

create table public.organization_email_verifications (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations (id) on delete cascade,
  token_hash text not null,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  consumed_at timestamptz,
  constraint organization_email_verifications_token_hash_length check (
    char_length(token_hash) = 64
  )
);

create index organization_email_verifications_organization_idx
  on public.organization_email_verifications (organization_id, created_at desc);

create unique index organization_email_verifications_token_hash_idx
  on public.organization_email_verifications (token_hash);

alter table public.organization_email_verifications enable row level security;

-- No policies are defined for anon/authenticated: combined with the
-- revoke below, this table is completely inaccessible from the browser
-- in every direction. Only SECURITY DEFINER functions (running as the
-- table owner) and service_role can touch it.
revoke all on table public.organization_email_verifications from anon, authenticated;

create function public.issue_organization_email_verification_token(
  target_organization_id uuid
)
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  raw_token text := encode(extensions.gen_random_bytes(32), 'hex');
begin
  if not exists (
    select 1 from public.organizations where id = target_organization_id
  ) then
    raise exception 'Organization not found.' using errcode = 'P0002';
  end if;

  delete from public.organization_email_verifications
  where organization_id = target_organization_id
    and consumed_at is null;

  insert into public.organization_email_verifications (
    organization_id,
    token_hash,
    expires_at
  ) values (
    target_organization_id,
    encode(extensions.digest(raw_token, 'sha256'), 'hex'),
    now() + interval '24 hours'
  );

  update public.organizations
  set official_email_verification_sent_at = now()
  where id = target_organization_id;

  return raw_token;
end;
$$;

-- Callable only by trusted server-side code (the Edge Function that
-- actually sends the email), never by anon or authenticated browser
-- sessions. This is the only path that ever learns the raw token.
revoke all on function public.issue_organization_email_verification_token(uuid)
  from public, anon, authenticated;
grant execute on function public.issue_organization_email_verification_token(uuid)
  to service_role;

create function public.verify_organization_email(
  target_organization_id uuid,
  raw_token text
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  matched_id uuid;
begin
  if raw_token is null or btrim(raw_token) = '' then
    return false;
  end if;

  select id into matched_id
  from public.organization_email_verifications
  where organization_id = target_organization_id
    and consumed_at is null
    and expires_at > now()
    and token_hash = encode(extensions.digest(raw_token, 'sha256'), 'hex')
  limit 1;

  if matched_id is null then
    return false;
  end if;

  update public.organization_email_verifications
  set consumed_at = now()
  where id = matched_id;

  update public.organizations
  set official_email_verified_at = now()
  where id = target_organization_id;

  return true;
end;
$$;

-- Intentionally callable by anon too: the person clicking the emailed
-- link may not have an active browser session. Security comes entirely
-- from possession of the single-use, short-lived, unguessable token —
-- never from auth.uid() or the organisation id alone.
revoke all on function public.verify_organization_email(uuid, text) from public;
grant execute on function public.verify_organization_email(uuid, text)
  to anon, authenticated;

-- ---------------------------------------------------------------------
-- 4. Lightweight duplicate-organisation signals.
--
-- Ordinary applicants receive booleans only (a gentle warning, no
-- private detail about the other organisation). Reviewers additionally
-- receive the matched organisation id/name so they can act on it during
-- review. The projection is enforced inside the function, not by UI
-- hiding.
-- ---------------------------------------------------------------------

create function public.check_duplicate_organization_signals(
  candidate_name text,
  candidate_official_email text default null,
  candidate_registration_number text default null,
  exclude_organization_id uuid default null
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  name_match boolean := false;
  email_match boolean := false;
  registration_match boolean := false;
  reviewer boolean;
  matches jsonb := '[]'::jsonb;
begin
  if (select auth.uid()) is null then
    raise exception 'Authentication is required.' using errcode = '42501';
  end if;

  reviewer := public.is_application_reviewer();

  select exists (
    select 1 from public.organizations o
    where btrim(coalesce(candidate_name, '')) <> ''
      and lower(btrim(o.name)) = lower(btrim(candidate_name))
      and (exclude_organization_id is null or o.id <> exclude_organization_id)
  ) into name_match;

  select exists (
    select 1 from public.organizations o
    where btrim(coalesce(candidate_official_email, '')) <> ''
      and lower(btrim(o.official_email)) = lower(btrim(candidate_official_email))
      and (exclude_organization_id is null or o.id <> exclude_organization_id)
  ) into email_match;

  select exists (
    select 1 from public.organizations o
    where btrim(coalesce(candidate_registration_number, '')) <> ''
      and lower(btrim(o.registration_number)) = lower(btrim(candidate_registration_number))
      and (exclude_organization_id is null or o.id <> exclude_organization_id)
  ) into registration_match;

  if reviewer and (name_match or email_match or registration_match) then
    select coalesce(jsonb_agg(jsonb_build_object('id', o.id, 'name', o.name)), '[]'::jsonb)
    into matches
    from public.organizations o
    where (exclude_organization_id is null or o.id <> exclude_organization_id)
      and (
        (btrim(coalesce(candidate_name, '')) <> ''
          and lower(btrim(o.name)) = lower(btrim(candidate_name)))
        or (btrim(coalesce(candidate_official_email, '')) <> ''
          and lower(btrim(o.official_email)) = lower(btrim(candidate_official_email)))
        or (btrim(coalesce(candidate_registration_number, '')) <> ''
          and lower(btrim(o.registration_number)) = lower(btrim(candidate_registration_number)))
      );
  end if;

  return jsonb_build_object(
    'nameMatch', name_match,
    'emailMatch', email_match,
    'registrationNumberMatch', registration_match,
    'matches', matches
  );
end;
$$;

revoke all on function public.check_duplicate_organization_signals(text, text, text, uuid)
  from public, anon;
grant execute on function public.check_duplicate_organization_signals(text, text, text, uuid)
  to authenticated;

-- ---------------------------------------------------------------------
-- 5. submit_organization_application: lean V2 required-field check.
--
-- The original function (20260821000000) enforces the previous, richer
-- intake form's required fields at the database layer — a genuine
-- deployment compatibility defect once the frontend collects a leaner
-- set. This replacement keeps every non-validation behaviour (ownership
-- check, status-transition check, review history insert) identical and
-- only narrows which fields are required to match the lean V2 wizard.
-- Fields no longer required here remain valid, writable columns for
-- later profile enrichment — nothing is removed from the schema.
-- ---------------------------------------------------------------------

create or replace function public.submit_organization_application(target_application_id uuid)
returns public.organization_applications
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_user_id uuid := (select auth.uid());
  application_record public.organization_applications;
  organization_record public.organizations;
  updated_application public.organization_applications;
begin
  if current_user_id is null then
    raise exception 'Authentication is required.' using errcode = '42501';
  end if;

  select * into application_record
  from public.organization_applications
  where id = target_application_id
  for update;

  if application_record.id is null then
    raise exception 'Organization application not found.' using errcode = 'P0002';
  end if;

  if not public.can_manage_organization(application_record.organization_id) then
    raise exception 'You cannot submit this organization application.' using errcode = '42501';
  end if;

  if application_record.status not in ('draft', 'needs_changes') then
    raise exception 'Only draft or changes-requested applications can be submitted.'
      using errcode = '22023';
  end if;

  select * into organization_record
  from public.organizations
  where id = application_record.organization_id;

  if organization_record.category is null
    or btrim(organization_record.name) = ''
    or btrim(organization_record.country) = ''
    or btrim(organization_record.region) = ''
    or btrim(organization_record.city) = ''
    or btrim(organization_record.official_email) = ''
    or organization_record.official_email !~* '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'
    or btrim(organization_record.official_phone) = ''
    or btrim(organization_record.description) = ''
    or organization_record.registration_status is null then
    raise exception 'Complete every required organization field before submission.'
      using errcode = '23514';
  end if;

  if btrim(application_record.representative_full_name) = ''
    or btrim(application_record.representative_email) = ''
    or application_record.representative_email !~* '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'
    or btrim(application_record.representative_phone) = ''
    or application_record.representative_relationship is null
    or not application_record.authorization_declaration
    or not application_record.accuracy_declaration then
    raise exception 'Complete the representative information and declarations before submission.'
      using errcode = '23514';
  end if;

  if organization_record.category = 'tamil_community'
    and not exists (
      select 1 from public.organization_tamil_community_details
      where organization_id = organization_record.id
        and btrim(subtype) <> ''
    ) then
    raise exception 'Complete the Tamil or community organization details before submission.'
      using errcode = '23514';
  elsif organization_record.category = 'education'
    and not exists (
      select 1 from public.organization_education_details
      where organization_id = organization_record.id
        and btrim(institution_type) <> ''
    ) then
    raise exception 'Complete the education organization details before submission.'
      using errcode = '23514';
  elsif organization_record.category = 'healthcare'
    and not exists (
      select 1 from public.organization_healthcare_details
      where organization_id = organization_record.id
        and btrim(facility_type) <> ''
    ) then
    raise exception 'Complete the healthcare organization details before submission.'
      using errcode = '23514';
  elsif organization_record.category = 'business'
    and not exists (
      select 1 from public.organization_business_details
      where organization_id = organization_record.id
        and btrim(business_type) <> ''
        and btrim(industry) <> ''
    ) then
    raise exception 'Complete the business organization details before submission.'
      using errcode = '23514';
  elsif organization_record.category = 'nonprofit'
    and not exists (
      select 1 from public.organization_nonprofit_details
      where organization_id = organization_record.id
        and btrim(subtype) <> ''
    ) then
    raise exception 'Complete the nonprofit organization details before submission.'
      using errcode = '23514';
  elsif organization_record.category = 'other'
    and not exists (
      select 1 from public.organization_other_details
      where organization_id = organization_record.id
        and btrim(organization_type) <> ''
        and btrim(primary_purpose) <> ''
    ) then
    raise exception 'Complete the organization details before submission.'
      using errcode = '23514';
  end if;

  update public.organization_applications
  set status = 'submitted',
      current_step = 3,
      admin_feedback = null,
      submitted_at = now(),
      reviewed_at = null,
      reviewed_by = null
  where id = target_application_id
  returning * into updated_application;

  insert into public.application_review_history (
    application_id,
    actor_user_id,
    previous_status,
    new_status
  ) values (
    target_application_id,
    current_user_id,
    application_record.status,
    'submitted'
  );

  return updated_application;
end;
$$;
